// Gemini AI Integration
// Using Gemini 2.5 Flash model with the provided API key

const GEMINI_API_KEY = 'AIzaSyDemiHqUVekPovaBmYn9AF8FLAJ7g2v8dU';
const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent';

export interface GeminiResponse {
  candidates: Array<{
    content: {
      parts: Array<{
        text: string;
      }>;
    };
    finishReason: string;
  }>;
}

export interface GeminiRequest {
  contents: Array<{
    parts: Array<{
      text: string;
    }>;
  }>;
  generationConfig?: {
    temperature?: number;
    topK?: number;
    topP?: number;
    maxOutputTokens?: number;
  };
  safetySettings?: Array<{
    category: string;
    threshold: string;
  }>;
}

export class GeminiModel {
  private apiKey: string;
  private baseUrl: string;

  constructor(apiKey: string = GEMINI_API_KEY) {
    this.apiKey = apiKey;
    this.baseUrl = GEMINI_API_URL;
  }

  /**
   * Generate content using Gemini 2.5 Flash
   */
  async generateContent(
    prompt: string,
    options?: {
      temperature?: number;
      maxTokens?: number;
      topK?: number;
      topP?: number;
    }
  ): Promise<string> {
    try {
      const requestBody: GeminiRequest = {
        contents: [
          {
            parts: [
              {
                text: prompt
              }
            ]
          }
        ],
        generationConfig: {
          temperature: options?.temperature ?? 0.7,
          topK: options?.topK ?? 40,
          topP: options?.topP ?? 0.95,
          maxOutputTokens: options?.maxTokens ?? 2048
        },
        safetySettings: [
          {
            category: "HARM_CATEGORY_HARASSMENT",
            threshold: "BLOCK_MEDIUM_AND_ABOVE"
          },
          {
            category: "HARM_CATEGORY_HATE_SPEECH",
            threshold: "BLOCK_MEDIUM_AND_ABOVE"
          },
          {
            category: "HARM_CATEGORY_SEXUALLY_EXPLICIT",
            threshold: "BLOCK_MEDIUM_AND_ABOVE"
          },
          {
            category: "HARM_CATEGORY_DANGEROUS_CONTENT",
            threshold: "BLOCK_MEDIUM_AND_ABOVE"
          }
        ]
      };

      const response = await fetch(`${this.baseUrl}?key=${this.apiKey}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(requestBody)
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(`Gemini API error: ${response.status} - ${JSON.stringify(errorData)}`);
      }

      const data: GeminiResponse = await response.json();
      
      if (data.candidates && data.candidates.length > 0) {
        return data.candidates[0].content.parts[0].text;
      } else {
        throw new Error('No content generated by Gemini');
      }
    } catch (error) {
      console.error('Gemini API Error:', error);
      throw error;
    }
  }

  /**
   * Generate health and wellness advice
   */
  async generateWellnessAdvice(
    userInput: string,
    context?: {
      age?: number;
      symptoms?: string[];
      concerns?: string[];
    }
  ): Promise<string> {
    const contextPrompt = context ? `
User Context:
- Age: ${context.age || 'Not specified'}
- Symptoms: ${context.symptoms?.join(', ') || 'None mentioned'}
- Concerns: ${context.concerns?.join(', ') || 'None mentioned'}

` : '';

    const prompt = `${contextPrompt}User Query: ${userInput}

Please provide helpful, evidence-based health and wellness advice. Focus on:
1. General wellness guidance
2. Lifestyle recommendations
3. When to consult healthcare professionals
4. Self-care suggestions

Keep the response concise, empathetic, and professional. Remember to always recommend consulting with healthcare professionals for medical concerns.`;

    return this.generateContent(prompt, {
      temperature: 0.8,
      maxTokens: 1024
    });
  }

  /**
   * Generate symptom analysis
   */
  async analyzeSymptoms(
    symptoms: string[],
    additionalInfo?: string
  ): Promise<string> {
    const prompt = `Please analyze these symptoms and provide general guidance:

Symptoms: ${symptoms.join(', ')}
Additional Information: ${additionalInfo || 'None provided'}

Please provide:
1. Possible general causes (not medical diagnosis)
2. When to seek medical attention
3. General self-care recommendations
4. Important red flags to watch for

Remember: This is not a medical diagnosis. Always consult healthcare professionals for proper medical evaluation.`;

    return this.generateContent(prompt, {
      temperature: 0.7,
      maxTokens: 1024
    });
  }

  /**
   * Generate educational content about menopause
   */
  async generateMenopauseEducation(
    topic: string,
    level: 'beginner' | 'intermediate' | 'advanced' = 'beginner'
  ): Promise<string> {
    const levelInstructions = {
      beginner: 'Use simple language and basic concepts',
      intermediate: 'Use moderate complexity with some medical terms',
      advanced: 'Use detailed medical and scientific information'
    };

    const prompt = `Create educational content about menopause focusing on: ${topic}

Target Level: ${level}
Instructions: ${levelInstructions[level]}

Please include:
1. Clear explanation of the topic
2. Practical tips and advice
3. Common misconceptions
4. When to seek professional help
5. Resources for further learning

Keep the content accurate, helpful, and empowering.`;

    return this.generateContent(prompt, {
      temperature: 0.6,
      maxTokens: 1536
    });
  }

  /**
   * Generate personalized health report
   */
  async generateHealthReport(
    userData: {
      symptoms: string[];
      lifestyle: string[];
      concerns: string[];
      age?: number;
    }
  ): Promise<string> {
    const prompt = `Generate a personalized health and wellness report based on the following data:

User Profile:
- Age: ${userData.age || 'Not specified'}
- Current Symptoms: ${userData.symptoms.join(', ')}
- Lifestyle Factors: ${userData.lifestyle.join(', ')}
- Main Concerns: ${userData.concerns.join(', ')}

Please create a comprehensive report including:
1. Summary of current health status
2. Lifestyle recommendations
3. Symptom management strategies
4. Preventive measures
5. When to consult healthcare professionals
6. Actionable next steps

Format the report in a clear, organized manner with sections and bullet points.`;

    return this.generateContent(prompt, {
      temperature: 0.7,
      maxTokens: 2048
    });
  }

  /**
   * Generate motivational content
   */
  async generateMotivation(
    userMood: string,
    goals?: string[]
  ): Promise<string> {
    const goalsText = goals ? `Goals: ${goals.join(', ')}` : 'General wellness journey';
    
    const prompt = `Create motivational and encouraging content for someone who is feeling: ${userMood}

Context: ${goalsText}

Please provide:
1. Empathetic acknowledgment of their feelings
2. Positive affirmations
3. Practical encouragement
4. Small actionable steps they can take
5. Reminders of their strength and resilience

Keep the tone warm, supportive, and empowering.`;

    return this.generateContent(prompt, {
      temperature: 0.9,
      maxTokens: 512
    });
  }
}

// Export a default instance
export const geminiModel = new GeminiModel();

// Export utility functions
export const generateWellnessAdvice = (input: string, context?: any) => 
  geminiModel.generateWellnessAdvice(input, context);

export const analyzeSymptoms = (symptoms: string[], info?: string) => 
  geminiModel.analyzeSymptoms(symptoms, info);

export const generateMenopauseEducation = (topic: string, level?: 'beginner' | 'intermediate' | 'advanced') => 
  geminiModel.generateMenopauseEducation(topic, level);

export const generateHealthReport = (userData: any) => 
  geminiModel.generateHealthReport(userData);

export const generateMotivation = (mood: string, goals?: string[]) => 
  geminiModel.generateMotivation(mood, goals);
